myapp: 
    applictionName: myapp
    version: 3.5
    serverUrl: http://server/com
    serverName: server
    countries: 
      - USA
      - Germany
      - France
    user:
      firstname: hagos
      lastname: haftu
      username: fam
      password: nyefdae123
      